### ISSUE TITLE
Schlanke Settings Klasse

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-campo#11]
das Beste aus CMS-Basis und rrze-base, rrzw-wp und rrze-wp-extended nehmen und auf das Minimum reduzieren.

**Comment by xwolfde** [comment]
ich denke die Sache wie wir das in Person mit show und hide gemacht haben, hat sich bewährt und sollte übernommen werden. Das war auch das Ergebnis jahrelanger (nerviger) Erfahrung mit Einzelattributen.

**Comment by thenickless** [comment]
> ich denke die Sache wie wir das in Person mit show und hide gemacht haben, hat sich bewährt und sollte übernommen werden. Das war auch das Ergebnis jahrelanger (nerviger) Erfahrung mit Einzelattributen.

unbedingt :-D Ansonsten wäre das eine Fülle an Attributen.

Dieses Issue schließe ich, da es in https://github.com/RRZE-Webteam/rrze-campo/issues/23 enthalten ist.
