### ISSUE TITLE
Settings: Authkey

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-campo#19]
Für die Anbindung an DIP wird ein Authkey benutzt.
Mit dem Authkey wird der DIP-Support u.a. Ressourcen planen/zuweisen.

Damit soll man in den Einstellungen des Plugins einen AuthKey eintragen können, der beim Request verwendet wird.
Da wird allerdings das Plugin weiterhin öffentlich haben wollen und aber das Plugin bei >700 Multisite-Instanzen betreiben werden, ist es weder möglich, dass wir einen Default-Key im Code hinterlegen, noch dass wir bei jeder Instanz die irgendwann mal da ist oder hinzukommt, manuell den Wert vergeben und eintragen.

Daher soll es so sein, dass für den Authkey in den Plugin-Settings ein Eingabefeld existiert.
Wenn dieses Eingabefeld leer ist, wird geprüft ob es sich um eine Multisite-Instanz handelt in der das RRZE-Settings-Plugin aktiv ist. Wenn dieses aktiv ist, wird geschaut ob hier ein AuthKey gesetzt ist, der dann eben für alle Instanzen der Multisite gilt.
Dieser Authkey wird dann verwendet.
Wenn ein Authkey in den Settings gesetzt ist, hat dieses aber vorrang.

Ggf. sollte bei der Setting ein Link oder Info angegeben werden, wie man an einen persönlichen Authkey kommt.

**Comment by thenickless** [comment]
In rrze-campo 0.0.2 und rrze-settings 1.39.7 umgesetzt.
