### ISSUE TITLE
Eine Ausgabe der LV in 🪗 Akkordeonfächern oder als Liste für Lehrstuhlseiten?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-campo#20]
# Ein Attribut für übersichtlichere Ausgabe aller LV's eines Lehrstuhls
Die wichtigste Funktion ist weiterhin die Ausgabe von Veranstaltungen einer Einheit (Lehrstuhl, Co.) - Durch eine neue (optionale) Darstellung könnte neuen Webmastern die Ausgabe erleichtert werden.

(Die Idee basiert u.a. auch auf der neuen CRIS-Darstellung in Akkordeonfächern und der neuen Jobs-Ausgabe UTN )

## Ausgabe aller Veranstaltungen nach Typ in verschachtelten Akkordeons 🪗

Beispielsweise: http://pleione.lft.uni-erlangen.de/studium/vorlesungen/#collapse_0
Es könnte ein Attribut geben, dass die LV's nach Typ in verschachtelten Akkordeonfächern präsentiert.

(Eventuell wäre auch eine Ausgabe als Liste denkbar, ähnlich wie bei Jobs / UnivIS Personenausgabe)

### Begründung / Gedankengang:

Viele Lehrstuhlseiten versuchen Ihre Lehrveranstaltungen auf einer Inhaltsseite übersichtlich zu präsentieren.
Ohne den Einsatz von Akkordeonfächern / kompakten Listen wird die Seite v.a. für mobile Nutzer unübersichtlich lang. 

Lehrstuhlseiten könnten durch ein derartiges Attribut all Ihre Veranstaltungen mit Ihrer ID in einer schön strukturierten Übersicht ausgeben, ohne am Accordeon-Shortcode zu verzweifeln.

## Ausgabe einzelner Veranstaltungen als Akkordeonreiter

Ein schönes Beispiel mit einem einzelnen Eintrag, der in einem Akkordeon platziert wurde:
https://www.scientia.fau.de/studienangebot/aktuelles-programm/#FAU%20Scientia%20Vorlesungsreihe

## Ausgabe auf Personenseiten in Vita 

Auch auf Personenseiten werden LV's gerne eingebunden. Zwei Beispiele aus der Praxis:
https://www.sozdid.phil.fau.de/personen/jan-rauch/#collapse_2
https://www.romanistik.phil.fau.de/institut/mitarbeiterinnen/jansen/#collapse_0

Bei Dozenten mit sehr vielen LV's könnte eine Darstellung "Liste" ähnlich wie bei Jobs mehr Übersicht schaffen. Verschachtelte Akkordeons sind an der Stelle vermutlich schwer umzusetzen?

---
## Verwandte Helpdesk-Tickets zu UnivIS:
- Ausgabe individueller Lehrveranstaltungen in Akkordeonfächern | https://www.scientia.fau.de/studienangebot/aktuelles-programm/#FAU%20Scientia%20Vorlesungsreihe | http://go.fau.de/9sjp0 (22.03.2022)
- Ausgabe der Veranstaltungen des aktuellen Semesters getrennt nach Art der Veranstaltung und Semester in Akkordeonfächern | http://pleione.lft.uni-erlangen.de/studium/vorlesungen/#collapse_8 | http://go.fau.de/9sdv- (22.02.2022)
- Ausgabe der Veranstaltungen in einem Akkordeon nach Typ der Lehrveranstaltung | http://go.fau.de/9sccv (15.02.2022)
- Übersichtliche Ausgabe der LV der einzelnen Dozenten - Akkordeons? | https://www.sozdid.phil.fau.de/personen/jan-rauch/#collapse_2 | http://go.fau.de/9rwfu (04.11.2022)
- Übersicht der Lehrveranstaltungen in Akkordeons (Hardcoded) https://www.japanologie.phil.fau.de/studium/lehrveranstaltungen/#collapse_0 | http://go.fau.de/9rp5x (07.10.2021)

- Ausgabe der Lehrveranstaltungen einer Person (z.B. auf Kontaktseiten). Bsp.: https://www.romanistik.phil.fau.de/institut/mitarbeiterinnen/jansen/#collapse_0 | http://go.fau.de/9sqdq (22.04.2022)
- Übersichtliche Ausgabe der LV der einzelnen Dozenten - Akkordeons? | https://www.sozdid.phil.fau.de/personen/jan-rauch/#collapse_2 | http://go.fau.de/9rwfu (04.11.2022)

**Comment by cassandre** [comment]
In CRIS funktionieren die Accordion-Fächer über das Shortcode-Attribut `orderby`: Das gruppiert das Ergebnis-Array entsprechend und fügt Zwischenüberschriften bzw. Accordion-Fächer ein.

**Comment by thenickless** [comment]
so wie in CRIS funktioniert das auch so in rrze-UnivIS

**Comment by lukasniebler** [comment]
Mit welchem Attribut kann ich denn die Ausgabe als Akkordeon umsetzen?

Wenn ich jetzt z.B. den Shortcode auf einer Inhaltsseite habe:
[univis number="100100" task="lehrveranstaltungen-alle" lv_import="0" ]

**Comment by thenickless** [comment]
Dieses Issue schließe ich, da es in https://github.com/RRZE-Webteam/rrze-campo/issues/23 enthalten ist.
