### ISSUE TITLE
bestehende issues von fau-person, rrze-univis hier anlegen und dort hierher verweisen

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-campo#6]

**Comment by xwolfde** [comment]
Person eher nicht, siehe #18 .
Bei RRZE-UnivIS bin ich mir nicht sicher. Wenn wir da die issues übernehmen, holen wir uns gleich den Zopf der Althistorie mit. Es ist dann aber kein frischer Neuanfang.

Vielleicht wäre es besser nur die Fälle inhaltlich zu übernehmen, die gute funktionale Vorschläge haben, die wir auch hier haben wollen. Aber nicht Bugfixes oder ähnliches, was auf die alten UnivIS-Strukturen beruht, dei wir ja eh nicht merh nutzen wollen.

**Comment by thenickless** [comment]
einverstanden
